# Generated by Django 4.1 on 2022-10-29 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyectoFinalTolisanoPascaretta', '0002_fotoperfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppProyectoFinalTolisanoPascaretta.propietario'),
        ),
    ]
