# Generated by Django 4.1 on 2022-10-29 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyectoFinalTolisanoPascaretta', '0003_propiedad_propietario'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='inquilino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='AppProyectoFinalTolisanoPascaretta.inquilino'),
        ),
    ]
